#!/bin/bash
# PureVox - Linux payload staging (single implementation path).
# Copyright (C) 2024-2026 a2heng <752848283@qq.com>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Usage: bash tools/automation/stage_payload.sh <root-dir> <date-stamp>
# Assembles the /opt/purevox file tree (sources + models + html + server +
# pvplatform + pvengine + uitk + about + fonts + _build_version.py) under
# <root-dir>. Shared by pack_deb.sh, pack_rpm.sh and pack_appimage.sh, so the
# three formats can never ship different file sets. Launchers (.desktop,
# /usr/bin/purevox, AppRun), icons and the embedded interpreter stay in the
# per-format scripts: those are genuinely format-specific.
set -euo pipefail
ROOT="$1"
DATE="$2"

mkdir -p "$ROOT"
for f in \
    audio_processor.py config_manager.py about_content.py logger.py \
    model_config.py qr_tk.py run_tk.py user_paths.py wav_io.py session_plan.py; do
    cp "$f" "$ROOT/"
done
mkdir -p "$ROOT/models" "$ROOT/assets/icons" "$ROOT/assets/fonts"
cp models/*.onnx "$ROOT/models/"
cp assets/icons/*.ico "$ROOT/assets/icons/"
# Built-in pixel font (registered at runtime via the user fontconfig dir)
cp assets/fonts/*.ttf "$ROOT/assets/fonts/"
cp -r html "$ROOT/"
mkdir -p "$ROOT/server"
cp server/*.py "$ROOT/server/"
cp -r pvplatform "$ROOT/"
cp -r pvengine "$ROOT/"
cp -r uitk "$ROOT/"
cp -r about "$ROOT/"
find "$ROOT" -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true

cat > "$ROOT/_build_version.py" <<EOF
# Auto-generated by tools/automation/stage_payload.sh from tag/build time
BUILD_DATE = "$DATE"
EOF
